### ISSUE TITLE
请问有评估自己模型的脚本吗

### ISSUE THREAD

**Issue by JakChen797** [open-compass/LawBench#10]

**Comment by Yggdrasill7D6** [comment]
评估自己的模型可以使用两种方式：
第一种方式是自己在lawbench评测数据集上测试，得到推理结果，使用本项目中的评测脚本得到每个任务的分数。评测脚本地址 https://github.com/open-compass/LawBench/tree/main/evaluation 。
第二种方式是使用Opencompass评测框架，通过Opencompass来评测你的模型。Opencompass的使用文档 https://opencompass.org.cn/doc 。
希望这些信息能够为你提供帮助~
