### ISSUE TITLE
获取开源模型输出时，如何设定max_token

### ISSUE THREAD

**Issue by hydai99** [open-compass/LawBench#2]
你好，我正在尝试使用你们的数据在我自己本地的模型上运行。想问一下你们对于一些开源的模型，假设输入的prompt超过token数了，是如何处理的呢？

相关报错：
Invalid response object from API: '{"object":"error","message":"This model\'s maximum context length is 2048 tokens. However, you requested 2110 tokens (1086 in the messages, 1024 in the completion). Please reduce the length of the messages or completion.","code":40303}' (HTTP response code was 400)

**Comment by Leymore** [comment]
我们从左侧将输入的提示词进行截断，使得其满足模型的长度限制。

**Comment by hydai99** [comment]
> 我们从左侧将输入的提示词进行截断，使得其满足模型的长度限制。
方便给个参考吗？大概是怎么计算选取的？比如只用question不用instruction吗

**Comment by hydai99** [comment]
> 我们从左侧将输入的提示词进行截断，使得其满足模型的长度限制。

可以给个例子吗？大概是怎么确定截断的部分？

**Comment by Leymore** [comment]
例如输入如下：

```text
回答以下问题，只需直接给出法条内容:下面是一个例子:\n民法商法公司法第六十条的内容是什么？\n答案:一人有限责任公司章程由股东制定。\n请你回答：民法商法农民专业合作社法第一条的内容是什么？
```

那么假设模型的长度限制不足以支持输入全部的提示词，那么我们会从左侧进行截断，例如：

```text
第六十条的内容是什么？\n答案:一人有限责任公司章程由股东制定。\n请你回答：民法商法农民专业合作社法第一条的内容是什么？
```

如有更多问题，欢迎 reopen 该 issue。
