### ISSUE TITLE
9种法律专用大语言模型。

### ISSUE THREAD

**Issue by Trevo1** [open-compass/LawBench#3]
从one-shot和zero-shot的结果来看，怎么感觉这些专门训练的法律大模型表现不咋样呢？😂同参数以及甚至比不过更小参数的。
还是这是我的错觉 - -

**Comment by tonysy** [comment]
Right, generalist models exhibit superior performance over certain specialist models. These findings suggest that we ought to focus more on understanding how to develop specialized LLMs effectively.

**Comment by tonysy** [comment]
Feel free to re-open if needed.

**Comment by yucc-leon** [comment]
Another assessment shows similar results(https://github.com/WangRongsheng/CareGPT), except the top1 model, specicialist models performed comparably weak that genelist models.

But if looking close to the lawbench leaderboard, you will find specialist models work much better in several specific tasks than generalist models, which may suggest, in my opinion:
1. the generalist models are good on average but poor on any specific tasks, so perhaps none of them can be reliable for practical applications
2. the specialists performed better on various specific tasks but got poor overall scores, showing a trade-off between general and specific ablities

So I agree with @tonysy and more efficient methods are needed to train real domain expert models that beat generalist models and soon we can still keep their abilities as generalists:)
