### ISSUE TITLE
任务2-6的数据源与评测数据不匹配

### ISSUE THREAD

**Issue by lololo-xiao** [open-compass/LawBench#4]
在README.md中任务2-6（命名实体识别）的数据源为[CAIL2022](https://github.com/china-ai-law-challenge/CAIL2022/tree/main/xxcq)，此数据源中的命名实体识别任务是关于涉毒案件的人名，地点，时间，毒品类型以及毒品重量的识别

在data/one_shot/2-6.json和data/zero_shot/2-6.json文件中，提取的实体为盗窃案相关实体类型，下面是data/zero_shot/2-6.json中的sample

```
[
  {
    "instruction": "依据给出的实体类型提取句子的实体信息，实体类型包括:犯罪嫌疑人、受害人、被盗货币、物品价值、盗窃获利、被盗物品、作案工具、时间、地点、组织机构。逐个列出实体信息。",
    "question": "句子:破案后，公安机关将查获手机依法返还给了被害人严某某、肖某某。",
    "answer": "受害人:严某某、肖某某;被盗物品:查获手机;组织机构:公安机关"
  },
{...}
]
```

**Comment by Yggdrasill7D6** [comment]
感谢你指出这一点，任务2-6（命名实体识别）的数据源为[CAIL2021](https://github.com/china-ai-law-challenge/CAIL2021/tree/main/xxcq)，我们更正了README.md中的信息。
